version: '3.9'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
    - 27017:27017
    volumes:
    - ./data
  flask-service:
build: 
    context: ./flask
    restart: always
   
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    environment:
      - MONGODB_HOST=mongodb"